import React, { useState } from 'react';
import { Activity, Heart, BarChart3, Shield, Upload, AlertCircle, CheckCircle2, Clock, FileText, Video, Database, Loader2, Copy, User, Calendar } from 'lucide-react';

const PulseNexusDashboard = () => {
  const [selectedPatient, setSelectedPatient] = useState(null);
  const [clinicalNote, setClinicalNote] = useState('');
  const [csvFile, setCsvFile] = useState(null);
  const [videoFile, setVideoFile] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [currentAgent, setCurrentAgent] = useState(null);
  const [analysisResult, setAnalysisResult] = useState(null);
  const [isCopied, setIsCopied] = useState(false);

  const patients = [
    { id: 305, name: 'Patient #305', status: 'Post-Op Day 3', age: 67, surgery: 'Cardiac Surgery' },
    { id: 412, name: 'Patient #412', status: 'Post-Op Day 1', age: 52, surgery: 'Hip Replacement' },
    { id: 523, name: 'Patient #523', status: 'Post-Op Day 5', age: 71, surgery: 'Thoracic Surgery' }
  ];

  const handleFileUpload = (file, type) => {
    if (type === 'csv') {
      setCsvFile(file);
    } else if (type === 'video') {
      setVideoFile(file);
    }
  };

  const handleDragOver = (e) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleDrop = (e, type) => {
    e.preventDefault();
    e.stopPropagation();
    const file = e.dataTransfer.files[0];
    if (file) {
      handleFileUpload(file, type);
    }
  };

  const handleAnalyze = async () => {
    if (!clinicalNote || !csvFile) {
      alert('Please provide clinical note and upload wearable data CSV');
      return;
    }

    setIsAnalyzing(true);
    setAnalysisResult(null);

    // Simulate agent workflow
    const agents = [
      { name: 'Data Analyst', duration: 2000 },
      { name: 'Clinical Core', duration: 2500 },
      { name: 'Bio Sentry', duration: 1500 }
    ];

    for (const agent of agents) {
      setCurrentAgent(agent.name);
      await new Promise(resolve => setTimeout(resolve, agent.duration));
    }

    // Simulate analysis result
    const mockResult = {
      riskLevel: 'yellow',
      riskLabel: 'Watch Closely',
      reasoning: [
        'SpO2 levels dropped to 92% at 03:15 AM (normal range: 95-100%)',
        'Heart rate variability decreased by 15% from baseline',
        'Gait analysis shows slight imbalance in left leg (post-surgical side)',
        'AHA guidelines (2023) recommend close monitoring for SpO2 <94% in post-cardiac patients'
      ],
      handoverNote: `Patient #${selectedPatient.id} - Post-Op Day 3 Status Update

RISK ASSESSMENT: ⚠️ WATCH CLOSELY

KEY FINDINGS:
• SpO2 drop to 92% overnight (03:15 AM)
• Decreased heart rate variability (-15% from baseline)
• Gait asymmetry noted on surgical side
• No acute distress signs observed

RECOMMENDATIONS:
1. Increase vital signs monitoring frequency to q2h
2. Consider supplemental oxygen if SpO2 remains <94%
3. Physical therapy evaluation for gait assessment
4. Continue current medication regimen
5. Notify attending if SpO2 <90% or symptoms worsen

GUIDELINE REFERENCE: AHA Post-Cardiac Surgery Monitoring Protocol (2023)

Generated by Pulse Nexus AI - ${new Date().toLocaleString()}`
    };

    setAnalysisResult(mockResult);
    setCurrentAgent(null);
    setIsAnalyzing(false);
  };

  const copyToClipboard = () => {
    if (analysisResult) {
      navigator.clipboard.writeText(analysisResult.handoverNote);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    }
  };

  const getRiskColor = (level) => {
    switch (level) {
      case 'green': return 'bg-green-500';
      case 'yellow': return 'bg-yellow-500';
      case 'red': return 'bg-red-500';
      default: return 'bg-gray-500';
    }
  };

  const getRiskIcon = (level) => {
    switch (level) {
      case 'green': return <CheckCircle2 className="w-8 h-8" />;
      case 'yellow': return <AlertCircle className="w-8 h-8" />;
      case 'red': return <AlertCircle className="w-8 h-8" />;
      default: return <Clock className="w-8 h-8" />;
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-900 to-slate-900 text-white p-6">
      {/* Header */}
      <div className="max-w-7xl mx-auto mb-8">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Activity className="w-10 h-10 text-blue-400" />
            <div>
              <h1 className="text-4xl font-bold">Pulse Nexus</h1>
              <p className="text-slate-400">AI-Powered Clinical Decision Support</p>
            </div>
          </div>
          <div className="text-right text-sm">
            <p className="text-slate-400">Connected to Backend</p>
            <p className="text-green-400 flex items-center gap-2 justify-end">
              <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse"></span>
              localhost:8000
            </p>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto space-y-6">
        {/* Patient Selection */}
        <div className="bg-slate-800/50 rounded-lg p-6">
          <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
            <User className="w-5 h-5" />
            Select Patient Profile
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {patients.map(patient => (
              <button
                key={patient.id}
                onClick={() => setSelectedPatient(patient)}
                className={`p-4 rounded-lg border-2 transition-all text-left ${
                  selectedPatient?.id === patient.id
                    ? 'border-blue-500 bg-blue-500/20'
                    : 'border-slate-700 bg-slate-800/30 hover:border-slate-600'
                }`}
              >
                <div className="flex items-center gap-3 mb-2">
                  <div className="w-10 h-10 bg-blue-500 rounded-full flex items-center justify-center font-bold">
                    {patient.id}
                  </div>
                  <div>
                    <h3 className="font-semibold">{patient.name}</h3>
                    <p className="text-xs text-slate-400">{patient.status}</p>
                  </div>
                </div>
                <div className="text-xs text-slate-400 space-y-1">
                  <p>Age: {patient.age} years</p>
                  <p>Procedure: {patient.surgery}</p>
                </div>
              </button>
            ))}
          </div>
        </div>

        {/* Input Zone */}
        <div className="bg-slate-800/50 rounded-lg p-6">
          <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
            <FileText className="w-5 h-5" />
            Input Zone - Clinical Status
          </h2>
          <textarea
            value={clinicalNote}
            onChange={(e) => setClinicalNote(e.target.value)}
            placeholder="Enter patient's current status... (e.g., 'Patient reports feeling dizzy upon standing, mild shortness of breath')"
            className="w-full h-32 bg-slate-700 rounded-lg px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 resize-none"
          />
        </div>

        {/* Data Upload Zone */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* CSV Upload */}
          <div className="bg-slate-800/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
              <Database className="w-5 h-5" />
              Wearable Data Upload
            </h2>
            <div
              onDragOver={handleDragOver}
              onDrop={(e) => handleDrop(e, 'csv')}
              className={`border-2 border-dashed rounded-lg p-8 text-center transition-all cursor-pointer ${
                csvFile
                  ? 'border-green-500 bg-green-500/10'
                  : 'border-slate-600 hover:border-blue-500 hover:bg-slate-700/50'
              }`}
              onClick={() => document.getElementById('csv-input').click()}
            >
              <input
                id="csv-input"
                type="file"
                accept=".csv"
                onChange={(e) => handleFileUpload(e.target.files[0], 'csv')}
                className="hidden"
              />
              {csvFile ? (
                <div className="space-y-2">
                  <CheckCircle2 className="w-12 h-12 mx-auto text-green-400" />
                  <p className="font-semibold text-green-400">{csvFile.name}</p>
                  <p className="text-xs text-slate-400">Click to replace</p>
                </div>
              ) : (
                <div className="space-y-2">
                  <Upload className="w-12 h-12 mx-auto text-slate-400" />
                  <p className="font-semibold">Drop CSV file here</p>
                  <p className="text-xs text-slate-400">or click to browse</p>
                  <p className="text-xs text-slate-500 mt-2">wearable_samples.csv</p>
                </div>
              )}
            </div>
          </div>

          {/* Video Upload */}
          <div className="bg-slate-800/50 rounded-lg p-6">
            <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
              <Video className="w-5 h-5" />
              Gait Video Upload (Optional)
            </h2>
            <div
              onDragOver={handleDragOver}
              onDrop={(e) => handleDrop(e, 'video')}
              className={`border-2 border-dashed rounded-lg p-8 text-center transition-all cursor-pointer ${
                videoFile
                  ? 'border-green-500 bg-green-500/10'
                  : 'border-slate-600 hover:border-blue-500 hover:bg-slate-700/50'
              }`}
              onClick={() => document.getElementById('video-input').click()}
            >
              <input
                id="video-input"
                type="file"
                accept="video/*"
                onChange={(e) => handleFileUpload(e.target.files[0], 'video')}
                className="hidden"
              />
              {videoFile ? (
                <div className="space-y-2">
                  <CheckCircle2 className="w-12 h-12 mx-auto text-green-400" />
                  <p className="font-semibold text-green-400">{videoFile.name}</p>
                  <p className="text-xs text-slate-400">Click to replace</p>
                </div>
              ) : (
                <div className="space-y-2">
                  <Upload className="w-12 h-12 mx-auto text-slate-400" />
                  <p className="font-semibold">Drop video file here</p>
                  <p className="text-xs text-slate-400">or click to browse</p>
                  <p className="text-xs text-slate-500 mt-2">gait_video.mp4</p>
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Analyze Button */}
        <div className="flex justify-center">
          <button
            onClick={handleAnalyze}
            disabled={isAnalyzing || !selectedPatient || !clinicalNote || !csvFile}
            className="bg-blue-600 hover:bg-blue-700 disabled:bg-slate-600 disabled:cursor-not-allowed px-12 py-4 rounded-lg font-semibold text-lg transition-all flex items-center gap-3 shadow-lg"
          >
            {isAnalyzing ? (
              <>
                <Loader2 className="w-6 h-6 animate-spin" />
                Analyzing...
              </>
            ) : (
              <>
                <Activity className="w-6 h-6" />
                Analyze Patient
              </>
            )}
          </button>
        </div>

        {/* Agent Pulse */}
        {isAnalyzing && currentAgent && (
          <div className="bg-slate-800/70 rounded-lg p-6 border-2 border-blue-500 animate-pulse">
            <div className="flex items-center justify-center gap-4">
              <Loader2 className="w-8 h-8 animate-spin text-blue-400" />
              <div>
                <p className="font-semibold text-lg">{currentAgent} is working...</p>
                <p className="text-sm text-slate-400">
                  {currentAgent === 'Data Analyst' && 'Scanning vital signs and wearable data'}
                  {currentAgent === 'Clinical Core' && 'Analyzing clinical guidelines and protocols'}
                  {currentAgent === 'Bio Sentry' && 'Checking biosecurity alerts and risk factors'}
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Decision Zone */}
        {analysisResult && !isAnalyzing && (
          <div className="space-y-6">
            {/* Risk Badge */}
            <div className={`${getRiskColor(analysisResult.riskLevel)} rounded-lg p-8 text-center shadow-2xl`}>
              <div className="flex items-center justify-center gap-4 mb-4">
                {getRiskIcon(analysisResult.riskLevel)}
                <h2 className="text-4xl font-bold">{analysisResult.riskLabel}</h2>
              </div>
              <p className="text-lg opacity-90">{selectedPatient.name} - {selectedPatient.status}</p>
            </div>

            {/* The "Why" - Reasoning */}
            <div className="bg-slate-800/50 rounded-lg p-6">
              <h2 className="text-xl font-semibold mb-4 flex items-center gap-2">
                <Heart className="w-5 h-5" />
                Clinical Reasoning
              </h2>
              <ul className="space-y-3">
                {analysisResult.reasoning.map((reason, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <span className="w-6 h-6 bg-blue-500 rounded-full flex items-center justify-center text-sm font-bold flex-shrink-0 mt-0.5">
                      {index + 1}
                    </span>
                    <p className="text-slate-200">{reason}</p>
                  </li>
                ))}
              </ul>
            </div>

            {/* The Handover */}
            <div className="bg-slate-800/50 rounded-lg p-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-xl font-semibold flex items-center gap-2">
                  <FileText className="w-5 h-5" />
                  Clinical Handover Note
                </h2>
                <button
                  onClick={copyToClipboard}
                  className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg flex items-center gap-2 transition-all"
                >
                  {isCopied ? (
                    <>
                      <CheckCircle2 className="w-4 h-4" />
                      Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="w-4 h-4" />
                      Copy to Clipboard
                    </>
                  )}
                </button>
              </div>
              <pre className="bg-slate-900 rounded-lg p-4 text-sm text-slate-300 whitespace-pre-wrap font-mono overflow-x-auto">
                {analysisResult.handoverNote}
              </pre>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default PulseNexusDashboard;